[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "voting-system-backend"
sourceDir = "backend"
buildCommand = "npm install"
startCommand = "npm start"
healthcheckPath = "/health"

[[services]]
name = "voting-system-frontend"
sourceDir = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm run preview"
healthcheckPath = "/"

[services.voting-system-backend.envs]
NODE_ENV = "production"
PORT = "3000"
MYSQL_URL = "${{ MySQL.MYSQL_URL }}"

[services.voting-system-frontend.envs]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://backend-production-219d.up.railway.app/api" 